"use client";

/**
 * The Self client-SDK isolation seam (adapted from apps/wallet/app/self-client.ts).
 *
 * Every other client file imports `@selfxyz/qrcode` ONLY through this module, so the SDK dependency
 * is swappable/stubbable in one place. `@selfxyz/qrcode@1.0.24` is the installed, `version: 2`
 * (V2) SDK — the QR/deeplink builder that runs in the browser; the heavy backend verifier
 * (`@selfxyz/core`) is imported only server-side in api/self-verify/route.ts.
 */

import {
  SelfAppBuilder,
  getUniversalLink,
  SelfQRcodeWrapper,
  type SelfApp,
} from "@selfxyz/qrcode";

export { SelfQRcodeWrapper, getUniversalLink };
export type { SelfApp };

import { SELF_APP_NAME, SELF_SCOPE, SELF_ENDPOINT_TYPE } from "./config";
import {
  encodeDisclosureRequest,
  encodeV2IssuanceRequest,
  type DisclosureProfile,
} from "./lib/disclosure-profile";

/**
 * Build the Proof-of-Humanity SelfApp descriptor.
 *
 *   - `scope`        = the ONE canonical scope (matches the backend verifier, or it rejects).
 *   - `endpoint`     = the public URL of THIS app's `/api/self-verify` relay.
 *   - `endpointType` = "staging_https" (staging) or "https" (production), in lockstep with the
 *                      backend `mockPassport` flag (see config.ts SELF_ENV).
 *   - `userId`       = the connected EVM address (`userIdType: "hex"`). This binds the proof to the
 *                      wallet; the voucher recipient is the verified `userIdentifier`.
 *   - `userDefinedData` = a fixed disclosure-profile id plus a random 128-bit browser capability.
 *                      The backend enforces the age policy and requires that capability to poll the
 *                      short-lived result, so a wallet address alone cannot retrieve the credential.
 *   - `disclosures`  = OFAC is mandatory. Age and nationality are explicit user opt-ins used only
 *                      to prepare the holder's private predicate credential; they never enter the
 *                      soulbound token or a public attestation.
 *
 * Throws if `endpoint` is empty or a loopback URL — callers should catch and show the caveat.
 */
function buildSelfAppWithData(
  address: string,
  endpoint: string,
  profile: DisclosureProfile,
  userDefinedData: string,
): SelfApp {
  return new SelfAppBuilder({
    version: 2,
    appName: SELF_APP_NAME,
    scope: SELF_SCOPE,
    endpoint,
    endpointType: SELF_ENDPOINT_TYPE,
    userId: address,
    userIdType: "hex",
    userDefinedData,
    disclosures: {
      ofac: true,
      ...(profile.age ? { minimumAge: profile.age } : {}),
      ...(profile.nationality ? { nationality: true } : {}),
    },
  }).build();
}

export function buildSelfApp(address: string, endpoint: string, profile: DisclosureProfile, session: string): SelfApp {
  return buildSelfAppWithData(address, endpoint, profile, encodeDisclosureRequest(profile, session));
}

/**
 * Developer-facing v2 entry point. `credentialCommitment` must be generated by
 * the holder's private-credential prover/vault before passport verification.
 */
export function buildSelfIssuanceApp(
  address: string,
  endpoint: string,
  profile: DisclosureProfile,
  session: string,
  credentialCommitment: `0x${string}`,
): SelfApp {
  return buildSelfAppWithData(
    address,
    endpoint,
    profile,
    encodeV2IssuanceRequest(profile, session, credentialCommitment),
  );
}
